core/blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("post/<int:pk>", views.DetailView.as_view(), name="detail"),
    path("post/new", views.NewPostView.as_view(), name="new_post"),
    path("post/edit/<int:pk>", views.EditPostView.as_view(), name="edit_post"),
    path("post/delete/<int:pk>", views.DeletePostView.as_view(), name="delete_post"),
]

core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("account/", include("user.urls")),
    path("", include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/user/actions/password/urls.py
from django.urls import path

from user.actions.password import views

urlpatterns = [
    path("change/", views.PasswordChangeView.as_view(), name="password_change"),
    path(
        "change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

core/user/actions/update/urls.py
from django.urls import path

from user.actions.update import views

urlpatterns = [
    path("", views.SettingsView.as_view(), name="settings"),
    path("username/", views.UpdateUsernameView.as_view(), name="update_username"),
    path("password/", views.UpdatePasswordView.as_view(), name="update_password"),
    path("avatar/", views.UpdateAvatarView.as_view(), name="update_avatar"),
    path("name/", views.UpdateNameView.as_view(), name="update_name"),
    path("header/", views.UpdateHeaderView.as_view(), name="update_header")
]

core/blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class Post(models.Model):
    """
    Model for a blog post.

    .. py:attribute:: author

        The author of the post, defaults to: ::

            django.db.models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    .. py:attribute:: title

        The title of the post, defaults to: ::

            django.db.models.CharField(max_length=200)

    .. py:attribute:: text

        The plaintext of the post, defaults to: ::

            django.db.models.TextField()

    .. py:attribute:: image

        The image associated with the post defaults to: ::

            django.db.models.ImageField(blank=true, null=True, upload_to='images/%Y/%m/%d')

    .. py:attribute:: created

        The date and time the post was created, defaults to: ::

            created = models.DateTimeField(default=timezone.now, verbose_name=_("Date & Time Created"))

    .. py:attribute:: last_edited

        The date and time the post was last edited, defaults to: ::

            last_edited = models.DateTimeField(default=timezone.now, verbose=_("Date & Time Created"))
    """

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        help_text=_("Author of the post."),
        null=True,
        on_delete=models.CASCADE,
        related_name="posts",
    )
    title = models.CharField(help_text=_("Title of the post."), max_length=200)
    text = models.TextField(help_text=_("Text of the post."))
    image = models.ImageField(
        blank=True,
        help_text=_("Image uploaded with post."),
        null=True,
        upload_to="images/%Y/%m/%d",
    )
    created = models.DateTimeField(
        default=timezone.now, verbose_name=_("Date & Time Created")
    )
    last_edited = models.DateTimeField(
        auto_now=True, verbose_name=_("Date & Time Last Edited")
    )

    def __str__(self):
        """
        Returns the ``str`` version of the Post object.

        :returns: :py:attr:`title`
        :rtype: :py:class:`str`
        """
        return self.title

    @classmethod
    def get_authors_posts(cls, author):
        return cls.objects.filter(author_id=author.id).order_by("-created")

core/blog/forms.py
from django import forms

from .models import Post


# Forms
class PostForm(forms.ModelForm):
    """Form for editing and deleting a Post. Extends :py:class:`django.forms.ModelForm`."""

    class Meta:
        """
        Metadata for :py:class:`PostForm`.

        .. py:attribute:: fields
            :type: tuple

            Form fields. ::

                fields = ('title', 'text', 'image')

        .. py:attribute:: widgets
            :type: dict

            Form widgets. ::

                model = Post
                fields = ('title', 'text', 'image')
                widgets = {
                    'title': forms.TextInput(attrs={'class': 'form-control'}),
                    'text': forms.Textarea(attrs={'class': 'form-control'}),
                    'date_published': DateTimeWidget(attrs={'class': 'form-control'}),
                }
        """

        model = Post
        fields = ["title", "text", "image"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "text": forms.Textarea(attrs={"class": "form-control"}),
            "image": forms.ClearableFileInput(attrs={"class": "form-control"}),
        }

core/user/actions/password/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from django.utils.translation import gettext_lazy as _


class PasswordResetForm(auth_forms.PasswordResetForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(
            attrs={
                "autocomplete": "email",
                "class": "form-control",
                "placeholder": "Enter your email here...",
            }
        ),
    )


class SetPasswordForm(auth_forms.SetPasswordForm):
    new_password1 = forms.CharField(
        label=_("New Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "form-control",
                "placeholder": "Enter your new password here...",
            }
        ),
    )
    new_password2 = forms.CharField(
        label=_("Confirm New Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "form-control",
                "placeholder": "Enter your new password here...",
            }
        ),
    )

    field_order = ["new_password1", "new_password2"]


class PasswordChangeForm(auth_forms.PasswordChangeForm):
    old_password = forms.CharField(
        label=_("Old Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "autofocus": True,
                "class": "form-control",
                "placeholder": "Enter your old password here...",
            }
        ),
    )
    new_password1 = forms.CharField(
        label=_("New Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "form-control",
                "placeholder": "Enter your new password here...",
            }
        ),
    )
    new_password2 = forms.CharField(
        label=_("Confirm New Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "form-control",
                "placeholder": "Enter your new password here...",
            }
        ),
    )

    field_order = ["old_password", "new_password1", "new_password2"]

core/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .forms import PostForm
from .models import Post


class IndexView(generic.ListView):
    """
    The view class for the index view of the blog.

    .. py:attribute:: context_object_name
        :type: str

        The name of the object attached to the context data. ::

            context_object_name = 'posts'

    .. py:attribute:: template_name
        :type: str

        The name of the template used for the view. ::

            template_name = 'blog/index.html'
    """

    model = Post
    context_object_name = "posts"
    template_name = "blog/index.html"

    def get_queryset(self):
        """
        Return a :py:class:`QuerySet` of posts.

        :returns: A set of Posts published before the ``timezone.now()`` ordered by :py:attr:`blog.models.Post.created`
            (descending).
        :rtype: :py:class:`QuerySet`
        """
        return Post.objects.all().order_by("-created")


class DetailView(generic.DetailView):
    """
    The view class for the detail view of a post.

    .. py:attribute:: context_object_name
        :type: str

        The name of the object attached to the context data. ::

            context_object_name = 'posts'

    .. py:attribute:: template_name
        :type: str

        The name of the template used for the view. ::

            template_name = 'blog/detail.html'
    """

    model = Post
    context_object_name = "post"
    template_name = "blog/detail.html"


class NewPostView(LoginRequiredMixin, generic.CreateView):
    """
    The view class for the create view of a post.

    .. py:attribute:: context_object_name
        :type: str

        The name of the object attached to the context data. ::

            context_object_name = 'form'

    .. py:attribute:: template_name
        :type: str

        The name of the template used for the view. ::

            template_name = 'blog/post/actions/edit.html'
    """

    model = Post
    form_class = PostForm
    context_object_name = "form"
    template_name = "blog/post/actions/new.html"

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form. Returns to py:class:`IndexView`."""
        return reverse("index")

    def form_valid(self, form):
        """Update the instance's author to be the same as the user who made the request."""
        form.instance.author = self.request.user
        return super().form_valid(form)


class EditPostView(LoginRequiredMixin, generic.UpdateView):
    """
    The view class for the update view of a post.

    .. py:attribute:: context_object_name
        :type: str

        The name of the object attached to the context data. ::

            context_object_name = 'form'

    .. py:attribute:: template_name
        :type: str

        The name of the template used for the view. ::

            template_name = 'blog/post/actions/edit.html'
    """

    model = Post
    form_class = PostForm
    context_object_name = "form"
    template_name = "blog/post/actions/edit.html"

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form. Returns to py:class:`IndexView`."""
        return reverse("index")


class DeletePostView(LoginRequiredMixin, generic.DeleteView):
    """
    The view class for the delete view of a post.

    .. py:attribute:: context_object_name
        :type: str

        The name of the object attached to the context data. ::

            context_object_name = 'form'

    .. py:attribute:: template_name
        :type: str

        The name of the template used for the view. ::

            template_name = 'blog/post/actions/delete.html'
    """

    model = Post
    context_object_name = "post"
    template_name = "blog/post/actions/delete.html"

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form. Returns to :py:class:`IndexView`."""
        return reverse("index")

core/user/actions/password/views.py
from django.contrib.auth import views

from user.actions.password import forms


class PasswordResetView(views.PasswordResetView):
    form_class = forms.PasswordResetForm
    email_template_name = "user/password/reset_email.html"
    template_name = "user/password/reset_form.html"
    subject_template_name = "user/password/reset_subject.txt"


class PasswordResetDoneView(views.PasswordResetDoneView):
    template_name = "user/password/reset_done.html"


class PasswordResetConfirmView(views.PasswordResetConfirmView):
    form_class = forms.SetPasswordForm
    template_name = "user/password/reset_confirm.html"


class PasswordResetCompleteView(views.PasswordResetCompleteView):
    template_name = "user/password/reset_complete.html"


class PasswordChangeView(views.PasswordChangeView):
    form_class = forms.PasswordChangeForm
    template_name = "user/password/change_form.html"


class PasswordChangeDoneView(views.PasswordChangeDoneView):
    template_name = "user/password/change_done.html"

core/user/actions/update/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic import RedirectView, UpdateView
from django.urls import reverse

from user.actions.update import forms
from user.models import User


class SettingsView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse("update_username")


class UpdateUsernameView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = forms.UsernameForm
    template_name = "user/update/username.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse("update_username")


class UpdatePasswordView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = forms.PasswordForm
    template_name = "user/update/password.html"

    def form_valid(self, form):
        user = form.save()
        if user is not None:  # update current session credentials
            update_session_auth_hash(self.request, user)

        return HttpResponseRedirect(self.get_success_url())

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse("update_password")


class UpdateAvatarView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = forms.AvatarForm
    template_name = "user/update/avatar.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse("update_avatar")


class UpdateNameView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = forms.NameForm
    template_name = "user/update/name.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse("update_name")


class UpdateHeaderView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = forms.HeaderForm
    template_name = "user/update/header.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse("update_header")


class UpdateBioView(LoginRequiredMixin, UpdateView):
    model = User
    pass

core/blog/templates/blog/post/actions/delete.html
{% extends 'blog/base.html' %}

{% block content %}
{% if user.is_authenticated %}
    {% if form and post %}
        <h1>Delete</h1>
        <div class="container">
            <article class="post">
                <h2 class="post-title">{{ post.title }}</h2>
                {% include 'blog/post/post.html' %}
            </article>
            <form method="POST" class="post-form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mt-5 mb-3 d-block">
                    <input class="btn btn-danger" type="submit" value="Delete Post">
                </div>
            </form>
        </div>
    {% else %}
        <p>Something went wrong, no form...</p>
    {% endif %}
{% else %}
    <p>You shouldn't be here...</p>
{% endif %}
{% endblock %}

core/blog/templates/blog/post/actions/edit.html
{% extends 'blog/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        {% if form %}
            <div class="form-group">
                <form method="post" class="post-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div>
                        {% include 'blog/post/actions/action-bar.html' %}
                    </div>
                    <div class="mb-3">
                        <label for="title_id" class="form-label">Title:</label>
                        {{ form.title }}
                    </div>
                    <div class="mb-3">
                        <label for="id_author" class="form-label">Author:</label>
                        {{ form.author }}
                    </div>
                    <div class="mb-3">
                        <label for="id_text" class="form-label">Text:</label>
                        {{ form.text }}
                    </div>
                    <div class="mb-3">
                        <label for="id_image" class="form-label">Image:</label>
                        {{ form.image }}
                    </div>
                    <div class="mb-3">
                        <label for="id_date_published_0" class="form-label">Publish Date:</label>
                        {% for field in form.date_published %}
                            {{ field }}
                        {% endfor %}
                    </div>
                </form>
            </div>
        {% else %}
            <p>Something went wrong, the form was not loaded...</p>
        {% endif %}
    {% else %}
        <p>You shouldn't be here...</p>
    {% endif %}
    <script>
        var simplemde = new SimpleMDE({ element: document.getElementById("id_text") });
    </script>
{% endblock %}

core/blog/templates/blog/post/actions/form.html
{% block post_form %}
{% if user.is_authenticated %}
    {% if form %}
        {% if form.instance %}
            {% if form.instance.title %}
                <h2>{{ form.instance.title }}</h2>
            {% endif %}
        {% endif %}
        {% if form.errors %}
            {% for error in form.errors %}
                {{ error }}
            {% endfor %}
        {% endif %}
        {% if form.non_field_errors %}
            {% for non_field_error in form.non_field_errors %}
                <div class="alert alert-warning" role="alert">
                    <i class="bi bi-exclamation-diamond-fill"></i> {{ non_field_error }}
                </div>
            {% endfor %}
        {% endif %}
        {% for field in form %}
            <div class="my-3 form-row text-start">
                {% if field.errors %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger" role="alert">
                            <i class="bi bi-exclamation-diamond-fill"></i> {{ error }}
                        </div>
                    {% endfor %}
                {% endif %}
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}:</label>
                {{ field }}
            </div>
        {% endfor %}
    {% endif %}
{% endif %}
{% endblock %}

core/blog/templates/blog/post/actions/markdown_editor.html
{% block markdown_editor_script %}
<script>
    var simple_mde = new SimpleMDE({
        element: document.getElementById("id_text"),
        forceSync: true,
    });
</script>
{% endblock markdown_editor_script %}

core/blog/templates/blog/post/actions/new.html
{% extends 'blog/base.html' %}

{% block content %}
{% if user.is_authenticated %}
    {% if form %}
        <div class="form-group">
            <form method="post" class="post-form" enctype="multipart/form-data" action="{% url 'new_post' %}">
                {% csrf_token %}
                {% include 'blog/post/actions/form.html' %}
                <div class="mt-5 mb-3 d-block">
                    <input class="btn btn-primary" type="submit" value="Save New Post">
                </div>
            </form>
        </div>
    {% else %}
        <p>Something went wrong, the form was not loaded...</p>
    {% endif %}
{% else %}
    <p>You shouldn't be here...</p>
{% endif %}
{% block markdown_editor_script %}
{% include 'blog/post/actions/markdown_editor.html' %}
{% endblock markdown_editor_script %}
{% endblock %}